---
name: build-protos
on:
  pull_request:
    paths:
      - 'common-components/proto/**/*.proto'
jobs:
  build-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: bufbuild/buf-setup-action@v1.19.0

      - name: Verify proper formatting.
        run: buf build common-components/proto
